# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fontpage', '0004_auto_20161107_1131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
